---
  # Tasks: Ansible role pxe server.
  #
  # Author: Luc Rutten
  # Version: 1.0
  
  - name:  ""
  
  - name: "Install Packages"
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apache2
      - tftpd-hpa
      - inetutils-inetd
      - syslinux
    
  - name: "Configure /etc/default/tftpd-hpa"
    template:
      src: tftpd-hpa.j2
      dest: /etc/default/tftpd-hpa
      owner: root
      group: root
      mode: 0755
   
  - name: "Configure /etc/inetd.conf"
    lineinfile:
      path: /etc/inetd.conf
      line: 'tftp    dgram   udp    wait    root    /usr/sbin/in.tftpd /usr/sbin/in.tftpd -s /var/lib/tftpboot'
      backup: yes
  
  - name: "Configure boot menu - pxelinux.0 vesamenu.c32 memdisk"
    file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
      with_items:
    #    - { src: '/usr/lib/syslinux/pxelinux.0', dest: '/var/lib/tftpboot/pxelinux.0' }
        - { src: '/usr/lib/syslinux/modules/bios/vesa.c32', dest: '/var/lib/tftpboot/vesamenu.c32' }
        - { src: '/usr/lib/syslinux/memdisk', dest: '/var/lib/tftpboot/memdisk' }

  - name: "Configure boot menu - create directory /var/lib/tftpboot/pxelinux.cfg/"
    file:
      dest: /var/lib/tftpboot/pxelinux.cfg/
      state: directory
    
  - name: "Add Ubuntu 16.04 netinstall /var/lib/tftpboot/images/ubuntu/16.04/amd64"     
    file:
      dest: /var/lib/tftpboot/images/ubuntu/16.04/amd64
      state: directory
      
  - name: "Download Ubuntu 16.04 netinstall to /var/lib/tftpboot/images/ubuntu/16.04/amd64"
    get_url:
      url: http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/mini.iso
      dest: /var/lib/tftpboot/images/ubuntu/16.04/amd64/mini.iso
  
  - name: "Configure /var/lib/tftpboot/pxelinux.cfg/default"
    template:
      src: default.j2
      dest: /var/lib/tftpboot/pxelinux.cfg/default
      owner: root
      group: root
      mode: 0755
  